n = str(input('Qual o seu nome completo?')).strip()
print('Muito prazer em te conhecer!')
nome = n.split()
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome é {}'.format(nome[-1]))